stages:
  load_data:
    cmd: python3 src/stage_01_load_and_save_data.py --config=params.yaml
    deps:
      - src/stage_01_load_and_save_data.py
      - src/utils/common_utils.py
    params:
      - data_source.s3_source
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv
  split_data:
    cmd: python3 src/stage_02_split_data.py --config=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/common_utils.py
    params:
      - artifacts.raw_local_data
      - artifacts.split_data.processed_data_dir
      - artifacts.split_data.train_path
      - artifacts.split_data.test_path
      - base.random_state
      - base.test_size
      - base.target_col
    outs:
      - artifacts/processed_data/train.csv
      - artifacts/processed_data/test.csv
  train:
    cmd: python3 src/stage_03_train_model.py --config=params.yaml
    deps:
      - src/stage_03_train_model.py
      - artifacts/processed_data/train.csv
      - src/utils/common_utils.py
    params:
      - base.random_state
      - base.target_col
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
      - artifacts.split_data.train_path
    outs:
      - artifacts/saved_models/model.pkl
  evaluate:
    cmd: python3 src/stage_04_evaluate.py --config=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - artifacts/saved_models/model.pkl
      - src/utils/common_utils.py
      - artifacts/processed_data/test.csv
    params:
      - artifacts.split_data.test_path
      - base.target_col
      - artifacts.report.scores
    metrics:
      - artifacts/report/scores.json:
          cache: false
