base:
  project: simple-dvc-demo
  random_state: 42
  target_col: quality
  test_size: 0.2

data_source:
  s3_source: https://dvc-demo-datasets.s3.ap-south-1.amazonaws.com/winequality_data/winequality-red.csv

artifacts:
  artifacts_dir: artifacts

  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/data.csv

  split_data:
    processed_data_dir: artifacts/processed_data_dir
    train_path: artifacts/processed_data_dir/train.csv
    test_path: artifacts/processed_data_dir/test.csv
  report:
    report_dir: artifacts/report
    params: artifacts/report/params.json
    scores: artifacts/report/scores.json

  model_dir: artifacts/saved_models
  model_path: artifacts/saved_models/model.pkl

estimators:
  ElasticNet:
    params:
      alpha: 0.7
      l1_ratio: 0.4
